tittle: Samuel kibe
logo: /assets/port.jpeg
description: Data Science Portfolio || &Personal blog 
twitter_username: https://twitter.com/kibe_ish
github_username: https://github.com/samkibe

theme: jekyll-theme-minimal
